name: ChatGPT Code Commit & Push

on:
  push:
    branches:
      - main  # Change this to your primary branch name if different
  workflow_dispatch:  # Allows manual triggering of the action

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: "ChatGPT-Bot"
  GIT_AUTHOR_EMAIL: "chatgpt-bot@example.com"
  GIT_COMMIT_MESSAGE: "ChatGPT Auto-Commit: Code update for MegaPeers MVP"

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Ensures full history is available

      - name: Configure Git User
        run: |
          git config --global user.name "ChatGPT-Bot"
          git config --global user.email "chatgpt-bot@example.com"

      - name: Pull Latest Changes
        run: |
          git pull origin main

      - name: Generate & Save Code (ChatGPT)
        run: |
          echo "# ChatGPT Generated Code" > chatgpt_output.txt
          echo "# This file is auto-generated by ChatGPT in response to a request." >> chatgpt_output.txt

      - name: Commit Changes
        run: |
          git add .
          git commit -m "$GIT_COMMIT_MESSAGE" || echo "No changes to commit"

      - name: Push Changes
        run: |
          git push origin main
